### ISSUE TITLE
Use minicap inside app or just retrieve its secure virtual display

### ISSUE THREAD

**Issue by simontb** [openstf/minicap#101]
I do not need to stream the screen to another device, but instead want to use the images to further process them inside a `Service`. I currently use `MediaProjection` APIs for that, but as my app is no system app, I can't set VIRTUAL_DISPLAY_FLAG_SECURE.

Something like
`private native VirtualDisplay getSecureVirtualDisplay(Surface surface);`
inside my `Service` class would be perfect. Any hints how to achieve this?

I do not have the requirement as in #30 that I can't push via adb. It would be okay as well, If I were to push some code and then my .apk.

**Comment by sorccu** [comment]
Minicap is able to set the secure flag because the shell user is allowed to do that, at least for now. You cannot be the shell user in your app so it can't be done, though you could try creating a JNI to access the relevant method (see minicap source) and see if it lets you through.

I can't really help with that, though. And since this isn't directly minicap related, I will now close the issue to avoid polluting the issue list.
