### ISSUE TITLE
Local abstract

### ISSUE THREAD

**Issue by RPallas92** [openstf/minicap#31]
Hello,

Is it possible (with a rooted device) to forward the local abstract minicap to a tcp port from the device, like adb forward tcp:1717 localabstract:minicap, without using adb?

Thanks

**Comment by sorccu** [comment]
Not without writing or modifying code, I think. You should be able to use `android.net.LocalSocket` to connect to the minicap socket on the device, though.

**Comment by RPallas92** [comment]
Thanks, but it is not possible to connect with LocalSocket. It throws an IOException "Permission denied"

**Comment by oaux** [comment]
Hello,
use android.net.LocalSocket to connect to the minicap socket on the device,
new LocalSocketAddress("?", LocalSocketAddress.Namespace.ABSTRACT);
 public LocalSocketAddress(String name, LocalSocketAddress.Namespace namespace) {

**Comment by oaux** [comment]
Hello,
        use android.net.LocalSocket to connect to the minicap socket on the device,
        How to fill LocalSocketAddress  parameters？
              new LocalSocketAddress("?", LocalSocketAddress.Namespace.ABSTRACT);
  Thanks

**Comment by sorccu** [comment]
The name of the socket is `minicap`. I have not tried connecting from an app, but as @RPallas92 mentioned it seems to be restricted and you'd need root. Can't help with that.

**Comment by L-Kyle** [comment]
Did you solve this problem? I met the same event when I went to connect to the socket of minicap in APP
with a rooted device. new LocalSocketAddress("minicap", LocalSocketAddress.Namespace.ABSTRACT)  throws an IOException "Permission denied"   @RPallas92 @sorccu

**Comment by sorccu** [comment]
I don't have any rooted devices so I don't know. I suppose you should run your app as root or system somehow, or grant it some system-only permissions. Can't really help you with that, but please report back if you find a way.

**Comment by L-Kyle** [comment]
I have solved this problem in the afternoon ! It is caused by the rom of phone which is  made to  order. 
So , you know , you can't get through when you request permission due to the safety of rom. My phone is MI 4.  I flushed a new rom to it and rooted it . Now , it is running normal !
If you are using minicap in APP ,  remember to use  "LocalSocket" to connect to minicap instead of "Socket", like this :
LocalSocketAddress mLocalSocketAddress = new LocalSocketAddress("minicap",LocalSocketAddress.Namespace.ABSTRACT);
LocalSocket  mLocalSocket = new LocalSocket();
mLocalSocket.connect(mLocalSocketAddress);
InputStream    stream = mLocalSocket.getInputStream();
