### ISSUE TITLE
Build minicap for Android N (Preview)

### ISSUE THREAD

**Issue by haihaoshen** [openstf/minicap#32]
Hi,

I am trying to build minicap for Android N. Is there any instructions on how to do that? I would like to build from AOSO source code.

Thanks a lot!
-Harry

**Comment by sorccu** [comment]
Currently you can just copy the libs from the latest built version. Works
with N and M.

**Comment by haihaoshen** [comment]
Thanks a lo! As I found, the max version is android-23, which should support Android M. Do you mean it also supports Android N?

BTW, is there any way to build with AOSP code?

**Comment by sorccu** [comment]
Yes it does, just copy the libs under the new SDK name and it will work.

**Comment by sorccu** [comment]
You can build with AOSP if you update the build scripts, it's not a big task.

**Comment by haihaoshen** [comment]
Thanks for your information.

I found there are prebuilt libs under minicap/jni/minicap-shared/aosp/libs, which contains different android version from 9 to 23; while minicap/libs also generates one copy (single version) after using ndk-build. May I know what;s the single version here? Is it related with ndk-build version or something else?

One more question on build from AOSP code: where folder should I copy minicap/jni to aosp folder? aosp is a local folder, not from dock.

**Comment by sorccu** [comment]
Just take the folder called `android-23`. Duplicate it and name it `android-24`. It should now work.

**Comment by haihaoshen** [comment]
Got it for this question, thanks.

(pre-built in git) minicap/jni/minicap-shared/aosp/libs/android-23/arm64-v8a: minicap.so
(ndk-build newly) minicap/libs/arm64-v8a: minicap  minicap-nopie  minicap.so

What's the difference between two minicap.so files? Which version does the minicap.so (ndk-build) support?

**Comment by sorccu** [comment]
It doesn't support anything. It's just a [dummy library](https://github.com/openstf/minicap/blob/master/jni/minicap-shared/mock/Minicap.cpp) that makes the main codebase compile against the symbols in the shared library.

**Comment by haihaoshen** [comment]
got it, thanks again!

**Comment by varundtsfi** [comment]
I want to build the android AOSP with minicap without using docker. 
You have put on web 
https://github.com/openstf/minicap/tree/master/jni/minicap-shared

Now I have a fresh copy of android 9 AOSP and  minicap project which you have put on web. 
**repo init -u https://android.googlesource.com/platform/manifest
repo init -u https://android.googlesource.com/platform/manifest -b android-9.0.0_r3
repo sync.**

I ran . build/envsetup.sh

How to start the AOSP build for **arm64-v8a**
and After completed  the build process How to compile aosp with mincap project so that I can get minicap libs.

Please help me I want to learn this process with the help of all of you guys.
