### ISSUE TITLE
How to resize the screen data after start minicap

### ISSUE THREAD

**Issue by larryzhuo** [openstf/minicap#57]
I already start minicap use this command
```javascript
adb -s 076639630099c3a7 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@180x320/0
``` 
now i want to change visual 180*320 to 1080x1920, what should i do? thank you

**Comment by sorccu** [comment]
Restart minicap with the new parameters like the README says.

**Comment by larryzhuo** [comment]
just like this:
```javascript
adb -s 076639630099c3a7 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@1080x1920/0
```
to restart.   i have tried, but not work

**Comment by sorccu** [comment]
Did you kill the other minicap first?

**Comment by larryzhuo** [comment]
how can i kill it?

**Comment by sorccu** [comment]
Either Ctrl+C if you're running it manually or use the pid (visible in stdout and the banner in the socket output) to issue the `kill` command.

I'm sorry but I can't help you with this because honestly it's not worth my time, it's 99% likely just a simple user error that you could've solved by reading the README. For example, instead of saying "not work", you should provide a detailed description of what does not work, and include the full log output from the command.

If you provide more details and it's enough to prove that it's a real issue, then we can talk more.

**Comment by larryzhuo** [comment]
sorry, i see, i will remember for your suggestion.  thank you.
