### ISSUE TITLE
[Suggestion]build minicap-static

### ISSUE THREAD

**Issue by fishjam** [openstf/minicap#77]
I have a suggestion for build minicap static library, please consider it.
If there are minicap static library, people can build and link there app without build in AOSP, and doesn't need to set LD_LIBRARY_PATH while running.

Thank you very much.

BTW:
When I install and use [MobileCenter](http://mobilecenter.hpe.com/),  I found there are multi VncServer-X.Y app(such as VncServer-4.3, VncServer-7.1 etc.) in server\Agent\vnc_android\ARM\Release, I think they use same technology.

**Comment by sorccu** [comment]
That way you would have to build a different binary for each SDK level. So instead of 1 x `minicap` + N x `minicap.so` you'd end up with N x `minicap`. I don't see a huge benefit in doing that. You do not need AOSP either way as long as you're not modifying the minicap-shared source code.

An easier way would be to set the rpath option during build time so that the minicap binary automatically looks for the shared library in the same directory, which would remove the need to specify `LD_LIBRARY_PATH`.

However, keep in mind that minicap was built for STF. While you're of course free to use it as a stand-alone component any way you want, I personally do not have much interest in spending my time on that, as I don't have a use case where that would be necessary.

**Comment by sorccu** [comment]
Building N binaries would also increase the `ndk-build` build time by a factor of N, so I don't think that's a good idea overall. It would make the non-AOSP experience worse, too.

**Comment by fishjam** [comment]
ok, I got it. thank you for your response very much.
I will try to use rpath option.

**Comment by sorccu** [comment]
I will close this issue now but if you find a way to add the rpath option, please make a PR with that change and I will accept it, because it shouldn't break anything (you could still use LD_LIBRARY_PATH if you wanted).

**Comment by fishjam** [comment]
But could you build both share library and static library? since you already have the AOSP environment?

**Comment by sorccu** [comment]
Like I said I don't have a use case for that so no I don't think I'll do
that, it's just unnecessary trouble for me, plus it would only make the
already very slow build process even slower.
