### ISSUE TITLE
test minicap client

### ISSUE THREAD

**Issue by dckhole** [openstf/minicap#84]
I wrote a small python/gtk script (~100 lines, 1 file) to connect to a minicap TCP socket (using the adb forwarding described in the readme to get the unix socket off the phone) and display frames as it gets them. Obviously there's no input to the device, but might be useful for anyone else testing this component in isolation. If you'd like it in the repo, I can do the fork/pull request thing?

**Comment by sorccu** [comment]
Sorry for the late response. It's great that you've made that tool, but unfortunately if we add it to the repository it becomes our responsibility to keep it up to date. I don't really do any Python or GTK, so that would be a bit of a pain, honestly.

I would recommend publishing the example in a separate repository under your GitHub account, and then linking that here. That way people would be able to find it and enjoy your work.

But really though thanks for the offer! Appreciated.

**Comment by yuzhangbit** [comment]
@dckhole Nice work! Could you share it?
