### ISSUE TITLE
How to test the real FPS in my browser?(Chrome or Firefox)

### ISSUE THREAD

**Issue by Tierney0115** [openstf/minicap#9]
I searched the solution online but did not find a way to do this. How do you test the FPS to get the result 30-40 or 10-20? Thanks.

**Comment by Tierney0115** [comment]
By the way I am using STF and want to get the real FPS in time. Thanks.

**Comment by gunta** [comment]
We had this feature before, we'll add it back

**Comment by sorccu** [comment]
There used to be an FPS counter in the STF UI. Basically the FPS reported by STF was the speed at which the browser could receive and render frames. However, it's currently difficult to measure, since on newer Android versions we don't read a frame at all if there's no change on the screen. So most of the time it would probably show <1 FPS.

For one frame, all of this needs to happen:

1. Android notifies us there's a new frame (fast)
2. We lock the new frame (fast)
3. The frame is converted to JPEG (slow)
4. The JPEG data is sent via the ADB USB connection (slow)
5. Our Node.js application receives the data (fast)
6. The Node.js application sends the frame data over via WebSocket (fast)
7. The browser receives the data (fast)
8. The browser renders the data into `<canvas>` (speed depends on client specs)

Therefore, the measurable FPS is different at every point. The values mentioned in the README cover all steps and are a reasonable average based on our personal experience.

If you want to measure meaningful FPS, you should write your own application that reads data from the minicap socket over USB as quickly as possible, open an application that's always moving (perhaps a game) and count how many frames it has received.

**Comment by Tierney0115** [comment]
@gunta  @sorccu 
Thank you for your reply. Could you please add this feature back or just email me this piece of code since the FPS is really important for me at this time. Very appreciate.

**Comment by sorccu** [comment]
Perhaps eventually, but I'm too busy to do anything about it right now.

**Comment by Tierney0115** [comment]
OK. I will try to figure it out. Thank you anyway
